const { chromium } = require('playwright')

;(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1000, height: 700 } })
  const errors = []
  page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
  page.on('pageerror', (err) => errors.push(String(err)))
  await page.goto('http://localhost:5183/')
  await page.waitForTimeout(1000)
  await page.click('#prelude').catch(() => {})
  await page.waitForTimeout(500)
  await page.click('#start-button').catch(() => {})
  await page.waitForTimeout(1500)
  const g = await page.evaluateHandle(() => window.__game)
  const hasGame = await page.evaluate(() => !!window.__game)
  console.log('hasGame', hasGame)
  await page.click('[data-chapter="spring"]').catch(() => {})
  await page.waitForTimeout(4500)
  await page.click('#spring-intro-start').catch(() => {})
  await page.waitForTimeout(1500)
  // walk right a bit to trigger walk anim
  await page.keyboard.down('ArrowRight')
  await page.waitForTimeout(1200)
  await page.screenshot({ path: '_shot_wanderer_walk.png' })
  await page.keyboard.up('ArrowRight')
  await page.waitForTimeout(300)
  await page.screenshot({ path: '_shot_wanderer_idle.png' })
  await page.keyboard.down('Space')
  await page.waitForTimeout(200)
  await page.screenshot({ path: '_shot_wanderer_jump.png' })
  await page.keyboard.up('Space')
  console.log('errors:', JSON.stringify(errors.slice(0, 20), null, 2))
  await browser.close()
})()
